### ISSUE TITLE
unable to copy the dotfiles on minimal arch install

### ISSUE THREAD

**Issue by RipDr19** [1amSimp1e/dots#62]
hello, first of all, I love your dotfiles, and wanted to clone this repo in my minimal install but couldn't since the url have a symbol in it, if you can kindly remove that symbol it would be of great help since I or anyone else doing the same, won't need to install any other DM or TWM just to copy this repo. Thanks.

**Comment by 1amSimp1e** [comment]
aight got it. Thanks
