### ISSUE TITLE
Waybar workspace issue

### ISSUE THREAD

**Issue by Manicpressure** [1amSimp1e/dots#63]
For some reason the workspaces from 1-10 does not appear on my waybar. The one with japanese numbers instead of arabic numbers. Can you tell me how to fix this please?

**Comment by 1amSimp1e** [comment]
My configuration is the workspace number with Japanese. If you want to switch to Arabic numbers. You can change or add more number display on it. This file is on waybar `config` file in `~/.config/waybar`

```
    "wlr/workspaces": {
      "format": "{icon}",
      "on-click": "activate",
      "format-icons": {
        "1": "",
        "2": "",
        "3": "",
        "4": "",
        "5": "",
        "urgent": "",
        "active": "",
        "default": ""
      }
    },
```

Notify me if it doesn't work. Thanks!

**Comment by Manicpressure** [comment]
Using the format given above and copy pasting the japanese numbers, I managed to get it working. Thanks
