### ISSUE TITLE
Waybar battery

### ISSUE THREAD

**Issue by Manicpressure** [1amSimp1e/dots#64]
On waybar I dont get a battery indicator, and the backlight %thing is confusing because my laptop doesnt have backlight. I tried deleting it on config and style.css but its still there. Please help.

**Comment by 1amSimp1e** [comment]
First of all, about the battery indicator, you may look at [this](https://man.archlinux.org/man/waybar-battery.5.en) for more configuration. 

 And about the backlight thing, you just wanna remove it from that current modules, in this case it's `modules-right`.
```
// Original
"modules-right": ["tray", "backlight", "pulseaudio", "network", "battery", "clock", "custom/power-menu"],
```

```
// After removing backlight
"modules-right": ["tray", "pulseaudio", "network", "battery", "clock", "custom/power-menu"],
```

Notify me if it works, thanks!

**Comment by Manicpressure** [comment]
Thanks for the solution!
