### ISSUE TITLE
Security Issue 

### ISSUE THREAD

**Issue by KeyTamer** [1amSimp1e/dots#66]
Please remove [this link](https://github.com/1amSimp1e/dots/blob/balcony%F0%9F%9A%8A/configs/hypr/scripts/startpage.sh) from the repository and add it to the Git ignore list. This is essential due to a potential security risk associated with the file.

The script in question opens a network port, and if it fails to change its working directory (cd) correctly, it has the potential to expose all files in your home directory to all users within your network.

**Comment by KeyTamer** [comment]
Idea for improvement https://github.com/1amSimp1e/dots/pull/67

**Comment by 1amSimp1e** [comment]
Thank you so much. Imma look at it later

**Comment by KeyTamer** [comment]
Thank you for you dot files I love to use them every day, and thank you for pulling. I created pull request for the other branches tow. In case you would like to handle it that way.
