### ISSUE TITLE
I can't install without getting an error... 

### ISSUE THREAD

**Issue by Ocnaibill** [1amSimp1e/dots#68]
So I'm using the tutorial here from the official github, and every time I get an error in hyprland.conf blur settings.
I think the configuration is old? so, I started to "update" some lines, but every time I got an error like: configuration error on line 82 error setting value <true> for field <decoration:blur_new_optimizations>

or something like this.

sorry if I'm being dumb, I just couldn't find anything about this.

**Comment by 1amSimp1e** [comment]
Could you report which repository is causing the issue?

**Comment by Ocnaibill** [comment]
> Could you report which repository is causing the issue?

Sorry, i forgot to tell. Late Night, im was trying to use Late Night.

**Comment by palkyia** [comment]
I had the same issue, I had to move the blur settings into their own category under decorations in hyprland.conf

  blur {
      enabled=true
      size=6.8 
      new_optimizations = true   
      passes = 2      
    }

**Comment by Ocnaibill** [comment]
> I had the same issue, I had to move the blur settings into their own category under decorations in hyprland.conf
> 
> blur { enabled=true size=6.8 new_optimizations = true passes = 2 }
And just that made work?
