### ISSUE TITLE
Workspaces not showing on Waybar

### ISSUE THREAD

**Issue by MidnightSlicer** [1amSimp1e/dots#74]
After an update yesterday the workspaces stopped showing on Waybar. I am using hyprland-git and waybar-git on Arch Linux. I figured out that for some reason "wlr/workspaces" does not work anymore but "hyprland/workspaces" does, I assume a recent change in Hyprland caused it. I created a pull request #73 that makes the changes to the late-night branch so if someone could test it that would be great. If this fixes it on older updates of Hyprland than the changes can be made to the other branches as well.

**Comment by 1amSimp1e** [comment]
Appreciate it! I might take a look later and merge it.
