### ISSUE TITLE
How to change the location for weather update?

### ISSUE THREAD

**Issue by RipDr19** [1amSimp1e/dots#88]
I want to change the location for the weather module in the waybar since it is showing me weather updates for vietnam only, can you tell me how can I do that?

**Comment by rlychilplr** [comment]
To my knowledge the source of the weather info uses ip geolocation so it should be accurate.

If you want to hard-code a location you can edit your config.
Open this file in your favorite editor ``~/.config/waybar/scripts/weather.py``
On line 61 you should see: ``weather = requests.get("https://wttr.in/?format=j1").json()``
If you edit this to ex.  for New-York you get: ``weather = requests.get("https://wttr.in/new-york?format=j1").json()``

In your case this would amount to ``weather = requests.get("https://wttr.in/vietnam?format=j1").json()``

**Comment by RipDr19** [comment]
Thanks man it was really helpful
