### ISSUE TITLE
Wallpaper?

### ISSUE THREAD

**Issue by Rainax1** [1amSimp1e/dots#90]
Can you add wallpapers used in preview images , I like them

**Comment by rlychilplr** [comment]
Open ~/.config/hypr/hyprland.conf in your prefered editor
Search for swaybg (it should be at the top at roughly line 25)
Edit the line `exec-once=swaybg -o \* -i ~/.config/hypr/wallpapers/night.jpg -m fill` to
```
exec-once=swaybg -o \* -i /usr/share/hyprland/wall2.png -m fill
``` 
Change wall2.png to the image you want (wall0.png, wall1.png or keep it at wall2.png)

`/usr/share/hyprland/` is the directory where the default hyprland wallpapers are stored, you can ignore the hyprland.conf in this directory

**Comment by Rainax1** [comment]
Thank you for your help
